### ISSUE TITLE
Missing setter method in few generated classes

### ISSUE THREAD

**Issue by yonghaoy** [googleapis/java-container#820]
Thanks for stopping by to let us know something could be better!

Setter we would want: 
`ClusterAutoscalingOrBuilder.setAutoprovisioningNodePoolDefaults`
Then 
AutoprovisioningNodePoolDefaultsOrBuilder.setServiceAccount
`

Those setter exists in old versions https://javadoc.io/static/com.google.apis/google-api-services-container/v1-rev20220826-2.0.0/com/google/api/services/container/model/AutoprovisioningNodePoolDefaults.html#setServiceAccount-java.lang.String-
but removed recently.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-container/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4.  version(s):

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```java
// example
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by suztomo** [comment]
setAutoprovisioningNodePoolDefaults is available in https://github.com/googleapis/google-cloud-java/blob/0ba6aa7965caad238019f70254bc7273dfc2b8b2/java-container/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ClusterAutoscaling.java#L1607

setServiceAccount is available in https://github.com/googleapis/google-cloud-java/blob/main/java-container/proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AutoprovisioningNodePoolDefaults.java#L1441 
 (not "OrBuilder")
